# Generated by Django 6.0.2 on 2026-04-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_systemsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="auto_approve_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
