# Generated by Django 4.2.7 on 2026-01-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_add_alert_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='source_index',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='alert',
            table='alerts_alert',
        ),
    ]

