# Generated by Django 6.0.2 on 2026-03-16 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_alter_alert_options_alter_alert_alert_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='esintegrationconfig',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='webhookconfig',
            name='tenant_id',
        ),
    ]

