# Generated by Codex on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_remove_alert_tenant_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSyncSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('interval_seconds', models.IntegerField(default=300)),
                ('batch_size', models.IntegerField(default=500)),
                ('fetch_all', models.BooleanField(default=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, default='', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ESIntegrationConfigHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosts', models.TextField(blank=True)),
                ('index', models.CharField(default='alerts', max_length=128)),
                ('username', models.CharField(blank=True, max_length=128)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('use_ssl', models.BooleanField(default=False)),
                ('verify_certs', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]

