# Generated by Django 6.0.2 on 2026-04-14 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0005_ticket_ai_chat_message'),
        ('tickets', '0004_eventticket_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketaichatmessage',
            name='ticket',
            field=models.ForeignKey(db_column='ticket_number', on_delete=django.db.models.deletion.CASCADE, to='tickets.eventticket'),
        ),
    ]
