# Generated by Django 6.0.2 on 2026-04-14 12:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Action template name', max_length=200, unique=True)),
                ('category', models.CharField(choices=[('enrichment', 'Enrichment'), ('containment', 'Containment'), ('release', 'Release'), ('notification', 'Notification'), ('integration', 'Integration'), ('utility', 'Utility')], default='utility', help_text='Action category', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Action description')),
                ('action_type', models.CharField(help_text="Unique action type identifier (e.g., 'send_email', 'block_ip')", max_length=100, unique=True)),
                ('config_schema', models.JSONField(default=dict, help_text='JSON schema defining required/optional parameters')),
                ('default_config', models.JSONField(default=dict, help_text='Default configuration values')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Action Template',
                'verbose_name_plural': 'Action Templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SavedWorkflowNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('node_type', models.CharField(choices=[('action', 'Action Node'), ('condition', 'Condition Node'), ('start', 'Start Node'), ('end', 'End Node')], default='action', max_length=20)),
                ('node_category', models.CharField(default='utility', max_length=50)),
                ('action_type', models.CharField(blank=True, max_length=100)),
                ('action_config', models.JSONField(blank=True, default=dict)),
                ('timeout_seconds', models.PositiveIntegerField(default=300)),
                ('on_failure', models.CharField(choices=[('stop', 'Stop Workflow'), ('continue', 'Continue to Next Step'), ('retry', 'Retry Step'), ('skip', 'Skip to Next Step')], default='stop', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('retry_delay_seconds', models.PositiveIntegerField(default=30)),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_workflow_nodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['node_category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Workflow name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Workflow description')),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual Execution'), ('alert', 'On Alert Created'), ('ticket_created', 'On Ticket Created'), ('ticket_status', 'On Ticket Status Change'), ('scheduled', 'Scheduled'), ('webhook', 'External Webhook')], default='manual', help_text='What triggers this workflow', max_length=50)),
                ('trigger_conditions', models.JSONField(blank=True, default=dict, help_text='Filter conditions for automatic triggers (JSON)')),
                ('schedule_cron', models.CharField(blank=True, help_text="Cron expression for scheduled workflows (e.g., '0 */4 * * *')", max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this workflow active?')),
                ('is_draft', models.BooleanField(default=True, help_text='Is this a draft version?')),
                ('version', models.PositiveIntegerField(default=1, help_text='Workflow version number')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization')),
                ('edges', models.JSONField(blank=True, default=list, help_text='List of edge connections for visual workflow editor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this workflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_source', models.CharField(blank=True, help_text="What triggered this execution (e.g., 'ticket:SEC-001', 'manual')", max_length=200)),
                ('trigger_data', models.JSONField(default=dict, help_text='Data from the trigger event')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='pending', help_text='Current execution status', max_length=20)),
                ('current_step', models.PositiveIntegerField(default=0, help_text='Index of the currently executing step')),
                ('total_steps', models.PositiveIntegerField(default=0, help_text='Total number of steps')),
                ('completed_steps', models.PositiveIntegerField(default=0, help_text='Number of completed steps')),
                ('progress_percent', models.FloatField(default=0.0, help_text='Execution progress percentage')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_data', models.JSONField(default=dict, help_text='Aggregated results from all steps')),
                ('error_message', models.TextField(blank=True, help_text='Error message if execution failed')),
                ('context', models.JSONField(default=dict, help_text='Execution context (variables, step outputs)')),
                ('task_result_id', models.CharField(blank=True, default='', help_text='ID of the django.tasks TaskResult for this execution', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_by', models.ForeignKey(blank=True, help_text='User who triggered this execution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_executions', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(help_text='Workflow being executed', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Execution',
                'verbose_name_plural': 'Workflow Executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('action', 'Action Node'), ('condition', 'Condition Node'), ('start', 'Start Node'), ('end', 'End Node')], default='action', help_text='Type of node in the visual workflow editor', max_length=20)),
                ('node_category', models.CharField(default='utility', help_text='Category used to group nodes in the visual workflow editor', max_length=50)),
                ('position_x', models.FloatField(default=0, help_text='X coordinate in the visual editor')),
                ('position_y', models.FloatField(default=0, help_text='Y coordinate in the visual editor')),
                ('order', models.PositiveIntegerField(default=0, help_text='Execution order (0-based)')),
                ('name', models.CharField(help_text='Step name/description', max_length=200)),
                ('action_type', models.CharField(help_text='Action type identifier (fallback if no template)', max_length=100)),
                ('action_config', models.JSONField(default=dict, help_text='Step-specific configuration parameters')),
                ('timeout_seconds', models.PositiveIntegerField(default=300, help_text='Maximum execution time in seconds')),
                ('on_failure', models.CharField(choices=[('stop', 'Stop Workflow'), ('continue', 'Continue to Next Step'), ('retry', 'Retry Step'), ('skip', 'Skip to Next Step')], default='stop', help_text='Action to take if step fails', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts')),
                ('retry_delay_seconds', models.PositiveIntegerField(default=30, help_text='Delay between retries in seconds')),
                ('condition', models.JSONField(blank=True, default=dict, help_text='Condition for executing this step (JSON expression)')),
                ('next_step_true', models.UUIDField(blank=True, help_text='Next step ID if condition evaluates to true', null=True)),
                ('next_step_false', models.UUIDField(blank=True, help_text='Next step ID if condition evaluates to false', null=True)),
                ('connections', models.JSONField(blank=True, default=list, help_text='List of connected step IDs for visual editor')),
                ('is_active', models.BooleanField(default=True, help_text='Is this step active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_template', models.ForeignKey(blank=True, help_text='Action template to use', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps', to='workflows.actiontemplate')),
                ('workflow', models.ForeignKey(help_text='Parent workflow', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Step',
                'verbose_name_plural': 'Workflow Steps',
                'ordering': ['workflow', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StepExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='pending', help_text='Current step status', max_length=20)),
                ('attempt_number', models.PositiveIntegerField(default=1, help_text='Current attempt number (for retries)')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('input_data', models.JSONField(default=dict, help_text='Input data passed to this step')),
                ('output_data', models.JSONField(default=dict, help_text='Output data from this step')),
                ('error_message', models.TextField(blank=True, help_text='Error message if step failed')),
                ('error_traceback', models.TextField(blank=True, help_text='Full error traceback')),
                ('logs', models.TextField(blank=True, help_text='Execution logs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow_execution', models.ForeignKey(help_text='Parent workflow execution', on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='workflows.workflowexecution')),
                ('step', models.ForeignKey(help_text='Step being executed', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='workflows.workflowstep')),
            ],
            options={
                'verbose_name': 'Step Execution',
                'verbose_name_plural': 'Step Executions',
                'ordering': ['workflow_execution', 'step__order'],
            },
        ),
    ]
