# Generated by Django 6.0.2 on 2026-02-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='edges',
            field=models.JSONField(blank=True, default=list, help_text='List of edge connections for visual workflow editor'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='connections',
            field=models.JSONField(blank=True, default=list, help_text='List of connected step IDs for visual editor'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='next_step_false',
            field=models.UUIDField(blank=True, help_text='Next step ID if condition evaluates to false', null=True),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='next_step_true',
            field=models.UUIDField(blank=True, help_text='Next step ID if condition evaluates to true', null=True),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='node_type',
            field=models.CharField(choices=[('action', 'Action Node'), ('condition', 'Condition Node'), ('start', 'Start Node'), ('end', 'End Node'), ('parallel', 'Parallel Node')], default='action', help_text='Type of node in the visual workflow editor', max_length=20),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='position_x',
            field=models.FloatField(default=0, help_text='X coordinate in the visual editor'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='position_y',
            field=models.FloatField(default=0, help_text='Y coordinate in the visual editor'),
        ),
    ]
