# Generated by Django 6.0.2 on 2026-02-16 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflow_edges_workflowstep_connections_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together=set(),
        ),
    ]
