# Generated by Django 6.0.2 on 2026-03-21 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflowexecution_task_result_id_and_more'),
        ('workflows', '0003_remove_unique_together_constraint'),
    ]

    operations = [
    ]
