# Generated by Django 4.2.7 on 2026-01-12 16:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('ticket_number', models.CharField(help_text='Unique ticket number (e.g., SEC20240501001)', max_length=100, primary_key=True, serialize=False)),
                ('event_siem_id', models.CharField(help_text='Original SIEM event ID from security device', max_length=255)),
                ('title', models.CharField(help_text='Short ticket title summarizing the incident', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed incident description', null=True)),
                ('event_impact', models.CharField(blank=True, help_text='Incident impact level (e.g., High/Medium/Low)', max_length=50, null=True)),
                ('event_scope', models.CharField(blank=True, help_text='Incident scope level (e.g., High/Medium/Low)', max_length=50, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('triaged', 'Triaged'), ('contained', 'Contained'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='New', help_text='Ticket status: New, Acknowledged, Triaged, Contained, Resolved, or Closed', max_length=50)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='Medium', help_text='Overall incident priority (Critical/High/Medium/Low by default)', max_length=50)),
                ('current_assign_group', models.CharField(blank=True, help_text='Current responsible team (e.g., SOC L1)', max_length=100, null=True)),
                ('current_assign_owner', models.CharField(blank=True, help_text="Current responsible person's name or account", max_length=100, null=True)),
                ('event_response_time', models.DateTimeField(blank=True, help_text='T3: Time when the incident was first responded to', null=True)),
                ('event_analysis_time', models.DateTimeField(blank=True, help_text='T4: Time when the incident analysis was completed', null=True)),
                ('event_containment_time', models.DateTimeField(blank=True, help_text='T5: Time when the incident was contained', null=True)),
                ('event_containment_cause', models.TextField(blank=True, help_text='Explanation of containment actions and rationale', null=True)),
                ('ticket_closure_user_id', models.CharField(blank=True, help_text='User ID of the person who closed the ticket', max_length=100, null=True)),
                ('ticket_resolved_time', models.DateTimeField(blank=True, help_text='T6: Time when the incident was marked as resolved', null=True)),
                ('ticket_closed_time', models.DateTimeField(blank=True, help_text='T7: Time when the ticket was officially closed', null=True)),
                ('event_level', models.CharField(blank=True, help_text='Incident severity level (e.g., P1/P2/P3)', max_length=50, null=True)),
                ('event_category', models.CharField(blank=True, help_text='Incident category (e.g., Intrusion, Suspicious Login)', max_length=100, null=True)),
                ('event_result', models.CharField(blank=True, help_text='Determination result (e.g., True Positive, False Positive)', max_length=100, null=True)),
                ('ticket_records', models.TextField(blank=True, help_text='Detailed handling results and notes', null=True)),
                ('event_cause_category', models.CharField(blank=True, help_text='Root cause classification', max_length=100, null=True)),
                ('ticket_stage', models.CharField(blank=True, help_text='Ticket stage (e.g., To Confirm, Investigating, Fixing)', max_length=50, null=True)),
                ('event_break_time', models.DateTimeField(blank=True, help_text='Interruption/downtime timestamp for tracking', null=True)),
                ('event_sources', models.CharField(blank=True, help_text='Event sources (e.g., SIEM, EDR, Firewall)', max_length=255, null=True)),
                ('event_platform', models.CharField(blank=True, help_text='Involved platform (e.g., Windows, Linux, AWS)', max_length=100, null=True)),
                ('ticket_url', models.URLField(blank=True, help_text='Related link (e.g., alert detail page)', max_length=500, null=True)),
                ('event_risk_score', models.IntegerField(blank=True, help_text='Risk score (0 to 100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ticket_category', models.CharField(blank=True, help_text='Ticket category (e.g., Security Incident, Compliance Check)', max_length=100, null=True)),
                ('alert_message', models.TextField(blank=True, help_text='Raw alert message content', null=True)),
                ('create_uid', models.CharField(blank=True, help_text='Creator user ID', max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag (0 = No, 1 = Yes)')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='Ticket creation time')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('progress_status', models.CharField(choices=[('in_progress', 'In Progress'), ('pending', 'Pending')], default='in_progress', help_text='Progress status for editability: In Progress or Pending', max_length=20)),
                ('assigned_user', models.ForeignKey(blank=True, help_text='Assigned Django user reference (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Ticket',
                'verbose_name_plural': 'Event Tickets',
                'db_table': 'event_ticket',
            },
        ),
        migrations.CreateModel(
            name='TicketSLA',
            fields=[
                ('ticket', models.OneToOneField(db_column='ticket_number', help_text='Reference to the associated event ticket', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sla', serialize=False, to='tickets.eventticket')),
                ('mtta_seconds', models.IntegerField(blank=True, help_text='Mean Time To Acknowledge in seconds (event_response_time - created_time)', null=True)),
                ('mtti_seconds', models.IntegerField(blank=True, help_text='Mean Time To Investigate in seconds (event_analysis_time - event_response_time)', null=True)),
                ('mttc_seconds', models.IntegerField(blank=True, help_text='Mean Time To Containment in seconds (event_containment_time - created_time)', null=True)),
                ('mttr_seconds', models.IntegerField(blank=True, help_text='Mean Time To Resolution in seconds (ticket_resolved_time - created_time)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='SLA record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='SLA record last update timestamp')),
            ],
            options={
                'verbose_name': 'Ticket SLA',
                'verbose_name_plural': 'Ticket SLAs',
                'db_table': 'ticket_sla',
            },
        ),
        migrations.CreateModel(
            name='TicketWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_entry', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(db_column='ticket_number', on_delete=django.db.models.deletion.CASCADE, to='tickets.eventticket')),
            ],
            options={
                'verbose_name': 'Work Log',
                'verbose_name_plural': 'Work Logs',
                'db_table': 'ticket_work_log',
            },
        ),
        migrations.CreateModel(
            name='TicketPendingInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(help_text='Timestamp when pending began')),
                ('ended_at', models.DateTimeField(blank=True, help_text='Timestamp when pending ended', null=True)),
                ('stage', models.CharField(help_text='Lifecycle stage for this pending interval (e.g., pre-acknowledge/investigate/containment/resolution)', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Optional notes/reason for pending interval', null=True)),
                ('ticket', models.ForeignKey(db_column='ticket_number', help_text='Reference to the associated event ticket', on_delete=django.db.models.deletion.CASCADE, related_name='pending_intervals', to='tickets.eventticket')),
            ],
            options={
                'verbose_name': 'Ticket Pending Interval',
                'verbose_name_plural': 'Ticket Pending Intervals',
                'db_table': 'ticket_pending_interval',
            },
        ),
        migrations.CreateModel(
            name='TicketHandleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.TextField(help_text='Description of the handling action')),
                ('handled_at', models.DateTimeField(auto_now_add=True)),
                ('handler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(db_column='ticket_number', on_delete=django.db.models.deletion.CASCADE, to='tickets.eventticket')),
            ],
            options={
                'verbose_name': 'Handling Log',
                'verbose_name_plural': 'Handling Logs',
                'db_table': 'ticket_handle_log',
            },
        ),
        migrations.CreateModel(
            name='NotificationSendMailJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('template_name', models.CharField(help_text="Email template used (e.g., 'new_ticket', 'escalation')", max_length=100)),
                ('context_data', models.JSONField(default=dict, help_text='Serialized context for rendering email template')),
                ('sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.ForeignKey(db_column='ticket_number', on_delete=django.db.models.deletion.CASCADE, to='tickets.eventticket')),
            ],
            options={
                'verbose_name': 'Email Notification Job',
                'verbose_name_plural': 'Email Notification Jobs',
                'db_table': 'notification_send_mail_job',
            },
        ),
        migrations.CreateModel(
            name='EventTicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='ticket_attachments/')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(db_column='ticket_number', on_delete=django.db.models.deletion.CASCADE, to='tickets.eventticket')),
                ('uploaded_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket Attachment',
                'verbose_name_plural': 'Ticket Attachments',
                'db_table': 'event_ticket_attachment',
            },
        ),
    ]
