# Generated by Django 4.2.7 on 2026-01-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventticket',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='Overall incident priority (Critical/High/Medium/Low by default)', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('triaged', 'Triaged'), ('contained', 'Contained'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', help_text='Ticket status: New, Acknowledged, Triaged, Contained, Resolved, or Closed', max_length=50),
        ),
    ]
