# Generated by Django 4.2.7 on 2026-01-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_eventticket_priority_alter_eventticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventticket',
            name='event_category',
            field=models.CharField(blank=True, choices=[('account_anomalies', 'Account Anomalies'), ('denial_of_service', 'Denial of Service'), ('malware', 'Malware'), ('system_anomalies', 'System Anomalies'), ('network_anomalies', 'Network Anomalies'), ('application_anomalies', 'Application Anomalies'), ('policy', 'Policy'), ('social_engineering', 'Social Engineering'), ('others', 'Others')], help_text='Incident category (e.g., Account Anomalies, Malware)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='event_result',
            field=models.CharField(blank=True, choices=[('true_positive', 'True Positive'), ('false_positive', 'False Positive'), ('true_positive_benign', 'True Positive - Benign')], help_text='Determination result (e.g., True Positive, False Positive)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='event_siem_id',
            field=models.CharField(blank=True, help_text='Original SIEM event ID from security device', max_length=255, null=True),
        ),
    ]
