# Generated by Django 6.0.2 on 2026-03-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_eventticket_event_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='labels',
            field=models.JSONField(blank=True, default=list, help_text='Ticket labels in [{label_name, label_value}] format'),
        ),
    ]
