apiVersion: apps/v1
kind: Deployment
metadata:
  name: siem-backend
  namespace: siem-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: siem-backend
  template:
    metadata:
      labels:
        app: siem-backend
    spec:
      imagePullSecrets:
        - name: aliyun-acr-secret
      securityContext:
        runASNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
      - name: django
        image: seclink-siem-cr-registry.cn-hangzhou.cr.aliyuncs.com/siem/siem-backend:v1.1
        ports:
        - containerPort: 8000
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: false
        env:
        - name: POSTGRES_DB
          value: "siem_db"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_HOST
          value: "siem-db"
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: siem-backend
  namespace: siem-dev
spec:
  selector:
    app: siem-backend
  ports:
  - port: 80
    targetPort: 8000