apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: siem-db
  namespace: siem-dev
spec:
  serviceName: "siem-db"
  replicas: 1
  selector:
    matchLabels:
      app: siem-db
  template:
    metadata:
      labels:
        app: siem-db
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999

      imagePullSecrets:
        - name: aliyun-acr-secret
      containers:
      - name: postgres
        image: seclink-siem-cr-registry.cn-hangzhou.cr.aliyuncs.com/siem/postgres:16
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: false
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "alicloud-disk-topology-alltype"
      resources:
        requests:
          storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: siem-db
  namespace: siem-dev
spec:
  selector:
    app: siem-db
  ports:
  - port: 5432