"""
Django settings for siem_project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR.parent / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'dev-secret-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'rest_framework',
    'rest_framework.authtoken',
    'accounts',
    'correlation',
    'integrations',
    'alerts',
    'dashboards',
    'tickets',
    'cmdb',
    'ai_assistant',
    'orchestrator',
    'workflows',
    'workflow_interfaces',
    'django_scheduled_tasks',
]

# ---------------------------------------------------------------------------
# Django 6.0 Background Tasks
# Uses ImmediateBackend: tasks run in-process as soon as .enqueue() is called.
# To run tasks truly asynchronously, switch BACKEND to a third-party backend
# (e.g. django-tasks-celery) that supports a separate worker process.
# ---------------------------------------------------------------------------
TASKS = {
    "default": {
        "BACKEND": "django.tasks.backends.immediate.ImmediateBackend",
    }
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'siem_project.token_auth_middleware.DRFTokenAuthMiddleware',
    'accounts.middleware.ReadonlyWriteBlockMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'siem_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'siem_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'siem_db'),
        'USER': os.getenv('POSTGRES_USER', 'siem_user'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'siem_password'),
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.getenv('DRF_THROTTLE_ANON_RATE', '60/min'),
        'user': os.getenv('DRF_THROTTLE_USER_RATE', '600/min'),
        'otp_request': os.getenv('OTP_REQUEST_RATE', '10/hour'),
        'otp_verify': os.getenv('OTP_VERIFY_RATE', '30/hour'),
        'audit_logs': os.getenv('AUDIT_LOGS_RATE', '120/hour'),
    },
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Django tasks backend (immediate execution by default).
# TASKS must be a dict of backends keyed by alias (default required).
TASKS = {
    'default': {
        'BACKEND': 'django.tasks.backends.immediate.ImmediateBackend',
    },
}

# Orchestrator schedule polling window (seconds).
ORCHESTRATOR_SCHEDULE_INTERVAL_SECONDS = int(os.getenv('ORCHESTRATOR_SCHEDULE_INTERVAL_SECONDS', '30'))


# OTP/Auth Registration settings
OTP_AUTH_ENABLED = os.getenv('OTP_AUTH_ENABLED', 'true').lower() in ('true', '1', 'yes')
OTP_EXPIRY_MINUTES = int(os.getenv('OTP_EXPIRY_MINUTES', '10'))
OTP_MAX_ATTEMPTS = int(os.getenv('OTP_MAX_ATTEMPTS', '5'))
OTP_RESEND_COOLDOWN_SECONDS = int(os.getenv('OTP_RESEND_COOLDOWN_SECONDS', '60'))
OTP_HASH_SECRET = os.getenv('OTP_HASH_SECRET', SECRET_KEY)
ADMIN_REGISTRATION_EMAILS = [
    x.strip() for x in os.getenv('ADMIN_REGISTRATION_EMAILS', '').split(',') if x.strip()
]
OTP_EMAIL_RETRY_ATTEMPTS = int(os.getenv('OTP_EMAIL_RETRY_ATTEMPTS', '3'))
OTP_EMAIL_RETRY_BACKOFF_SECONDS = float(os.getenv('OTP_EMAIL_RETRY_BACKOFF_SECONDS', '1'))
OTP_EMAIL_COOLDOWN_SECONDS = int(os.getenv('OTP_EMAIL_COOLDOWN_SECONDS', '60'))
OTP_EMAIL_LIMIT_COUNT = int(os.getenv('OTP_EMAIL_LIMIT_COUNT', '3'))
OTP_EMAIL_LIMIT_WINDOW_SECONDS = int(os.getenv('OTP_EMAIL_LIMIT_WINDOW_SECONDS', '600'))
OTP_IP_LIMIT_COUNT = int(os.getenv('OTP_IP_LIMIT_COUNT', '10'))
OTP_IP_LIMIT_WINDOW_SECONDS = int(os.getenv('OTP_IP_LIMIT_WINDOW_SECONDS', '300'))
REJECT_ADMIN_LIMIT_COUNT = int(os.getenv('REJECT_ADMIN_LIMIT_COUNT', '30'))
REJECT_ADMIN_LIMIT_WINDOW_SECONDS = int(os.getenv('REJECT_ADMIN_LIMIT_WINDOW_SECONDS', '3600'))
REJECT_IP_LIMIT_COUNT = int(os.getenv('REJECT_IP_LIMIT_COUNT', '30'))
REJECT_IP_LIMIT_WINDOW_SECONDS = int(os.getenv('REJECT_IP_LIMIT_WINDOW_SECONDS', '3600'))
AUDIT_LOG_RETENTION_DAYS = int(os.getenv('AUDIT_LOG_RETENTION_DAYS', '90'))

# Email delivery settings
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() in ('true', '1', 'yes')
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'false').lower() in ('true', '1', 'yes')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@localhost')
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '15'))
