"""
Django settings for siem_project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR.parent / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

_DEV_SECRET_KEY = 'dev-secret-key-change-in-production'
_PLACEHOLDER_SECRETS = {
    '',
    'xxx',
    'change-me',
    'change-me-in-production',
    'replace-me',
    'replace-with-a-generated-50-plus-character-random-secret',
    _DEV_SECRET_KEY,
}


def _env_bool(name: str, default: bool = False) -> bool:
    return os.getenv(name, str(default)).lower() in ('true', '1', 'yes', 'on')


def _env_int(name: str, default: int) -> int:
    try:
        return int(os.getenv(name, str(default)))
    except (TypeError, ValueError):
        return default


def _env_list(name: str, default: str = '') -> list[str]:
    return [x.strip() for x in os.getenv(name, default).split(',') if x.strip()]


# SECURITY WARNING: keep the secret key used in production secret.
SECRET_KEY = os.getenv('SECRET_KEY', _DEV_SECRET_KEY).strip()
if not DEBUG and SECRET_KEY in _PLACEHOLDER_SECRETS:
    raise ImproperlyConfigured('SECRET_KEY must be set to a non-placeholder value when DEBUG=False.')

ALLOWED_HOSTS = _env_list('ALLOWED_HOSTS', 'localhost,127.0.0.1')
if not DEBUG and '*' in ALLOWED_HOSTS:
    raise ImproperlyConfigured('ALLOWED_HOSTS must not contain "*" when DEBUG=False.')

# Workflow action credentials use a dedicated key ring. The first key is used
# for encryption; the rest are decryption-only fallbacks during key rotation.
WORKFLOW_ENCRYPTION_KEYS = _env_list('WORKFLOW_ENCRYPTION_KEYS')
if not DEBUG:
    if not WORKFLOW_ENCRYPTION_KEYS:
        raise ImproperlyConfigured(
            'WORKFLOW_ENCRYPTION_KEYS must contain at least one Fernet key when DEBUG=False.'
        )
    try:
        from cryptography.fernet import Fernet

        for workflow_encryption_key in WORKFLOW_ENCRYPTION_KEYS:
            Fernet(workflow_encryption_key.encode('ascii'))
    except (ImportError, TypeError, ValueError) as exc:
        raise ImproperlyConfigured(
            'WORKFLOW_ENCRYPTION_KEYS contains an invalid Fernet key or cryptography is unavailable.'
        ) from exc

CSRF_TRUSTED_ORIGINS = _env_list('CSRF_TRUSTED_ORIGINS')

# Production security hardening. Keep redirect/HSTS configurable because some
# deployments terminate TLS before Django, but default secure cookies in prod.
SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', False)
SECURE_HSTS_SECONDS = _env_int('SECURE_HSTS_SECONDS', 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
SECURE_HSTS_PRELOAD = _env_bool('SECURE_HSTS_PRELOAD', False)
SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', not DEBUG)
_SECURE_PROXY_SSL_HEADER = _env_list('SECURE_PROXY_SSL_HEADER')
if _SECURE_PROXY_SSL_HEADER and len(_SECURE_PROXY_SSL_HEADER) != 2:
    raise ImproperlyConfigured('SECURE_PROXY_SSL_HEADER must contain exactly two comma-separated values.')
SECURE_PROXY_SSL_HEADER = tuple(_SECURE_PROXY_SSL_HEADER) if _SECURE_PROXY_SSL_HEADER else None


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'rest_framework',
    'rest_framework.authtoken',
    'accounts',
    'correlation',
    'integrations',
    'alerts',
    'dashboards',
    'tickets',
    'cmdb',
    'ai_assistant',
    'orchestrator.apps.OrchestratorConfig',
    'workflows.apps.WorkflowsConfig',
    'workflow_interfaces',
    'detections',
    'risk',
    'django_scheduled_tasks',
]

# ---------------------------------------------------------------------------
# Django 6.0 Background Tasks
# Uses ImmediateBackend: tasks run in-process as soon as .enqueue() is called.
# To run tasks truly asynchronously, switch BACKEND to a third-party backend
# (e.g. django-tasks-celery) that supports a separate worker process.
# ---------------------------------------------------------------------------
TASKS = {
    "default": {
        "BACKEND": "django.tasks.backends.immediate.ImmediateBackend",
    }
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Compress large JSON responses such as the detection-rule catalog.
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'siem_project.token_auth_middleware.DRFTokenAuthMiddleware',
    'accounts.middleware.ReadonlyWriteBlockMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'siem_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'siem_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'siem_db'),
        'USER': os.getenv('POSTGRES_USER', 'siem_user'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'siem_password'),
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.getenv('DRF_THROTTLE_ANON_RATE', '60/min'),
        'user': os.getenv('DRF_THROTTLE_USER_RATE', '600/min'),
        'otp_request': os.getenv('OTP_REQUEST_RATE', '10/hour'),
        'otp_verify': os.getenv('OTP_VERIFY_RATE', '30/hour'),
        'audit_logs': os.getenv('AUDIT_LOGS_RATE', '120/hour'),
        'ticket_playbook_invoke': os.getenv('TICKET_PLAYBOOK_INVOKE_RATE', '20/min'),
    },
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Orchestrator schedule polling window (seconds).
ORCHESTRATOR_SCHEDULE_INTERVAL_SECONDS = int(os.getenv('ORCHESTRATOR_SCHEDULE_INTERVAL_SECONDS', '30'))

# Kibana Detection Engine proxy settings
KIBANA_BASE_URL = os.getenv('KIBANA_BASE_URL', '').rstrip('/')
KIBANA_API_KEY = os.getenv('KIBANA_API_KEY', '')
KIBANA_USERNAME = os.getenv('KIBANA_USERNAME', '')
KIBANA_PASSWORD = os.getenv('KIBANA_PASSWORD', '')
KIBANA_SPACE = os.getenv('KIBANA_SPACE', 'default')


# OTP/Auth Registration settings
OTP_AUTH_ENABLED = os.getenv('OTP_AUTH_ENABLED', 'true').lower() in ('true', '1', 'yes')
OTP_EXPIRY_MINUTES = int(os.getenv('OTP_EXPIRY_MINUTES', '10'))
OTP_MAX_ATTEMPTS = int(os.getenv('OTP_MAX_ATTEMPTS', '5'))
OTP_RESEND_COOLDOWN_SECONDS = int(os.getenv('OTP_RESEND_COOLDOWN_SECONDS', '60'))
OTP_HASH_SECRET = os.getenv('OTP_HASH_SECRET', SECRET_KEY).strip()
if not DEBUG and OTP_HASH_SECRET in _PLACEHOLDER_SECRETS:
    raise ImproperlyConfigured('OTP_HASH_SECRET must be unset or set to a non-placeholder value when DEBUG=False.')
ADMIN_REGISTRATION_EMAILS = [
    x.strip() for x in os.getenv('ADMIN_REGISTRATION_EMAILS', '').split(',') if x.strip()
]
OTP_EMAIL_RETRY_ATTEMPTS = int(os.getenv('OTP_EMAIL_RETRY_ATTEMPTS', '3'))
OTP_EMAIL_RETRY_BACKOFF_SECONDS = float(os.getenv('OTP_EMAIL_RETRY_BACKOFF_SECONDS', '1'))
OTP_EMAIL_COOLDOWN_SECONDS = int(os.getenv('OTP_EMAIL_COOLDOWN_SECONDS', '60'))
OTP_EMAIL_LIMIT_COUNT = int(os.getenv('OTP_EMAIL_LIMIT_COUNT', '3'))
OTP_EMAIL_LIMIT_WINDOW_SECONDS = int(os.getenv('OTP_EMAIL_LIMIT_WINDOW_SECONDS', '600'))
OTP_IP_LIMIT_COUNT = int(os.getenv('OTP_IP_LIMIT_COUNT', '10'))
OTP_IP_LIMIT_WINDOW_SECONDS = int(os.getenv('OTP_IP_LIMIT_WINDOW_SECONDS', '300'))
REJECT_ADMIN_LIMIT_COUNT = int(os.getenv('REJECT_ADMIN_LIMIT_COUNT', '30'))
REJECT_ADMIN_LIMIT_WINDOW_SECONDS = int(os.getenv('REJECT_ADMIN_LIMIT_WINDOW_SECONDS', '3600'))
REJECT_IP_LIMIT_COUNT = int(os.getenv('REJECT_IP_LIMIT_COUNT', '30'))
REJECT_IP_LIMIT_WINDOW_SECONDS = int(os.getenv('REJECT_IP_LIMIT_WINDOW_SECONDS', '3600'))
AUDIT_LOG_RETENTION_DAYS = int(os.getenv('AUDIT_LOG_RETENTION_DAYS', '90'))

# Email delivery settings
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'your_domain')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'your_email_address@your_domain')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() in ('true', '1', 'yes')
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'false').lower() in ('true', '1', 'yes')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@localhost')
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '15'))


# Prefect Workflow Engine
# PREFECT_API_URL: Prefect Server API endpoint (required for Prefect execution engine)
PREFECT_API_URL = os.getenv('PREFECT_API_URL', 'http://127.0.0.1:4200/api')
# PREFECT_DEPLOYMENT_ID: Default shared deployment ID for generic SOAR workflows
PREFECT_DEPLOYMENT_ID = os.getenv('PREFECT_DEPLOYMENT_ID', '')
# PREFECT_API_KEY: Optional API key for authentication with Prefect Cloud or self-hosted server
PREFECT_API_KEY = os.getenv('PREFECT_API_KEY', '')
